### ISSUE TITLE
libcob: Cannot find module 'EXEC_NODEJS'

### ISSUE THREAD

**Issue by MartinSandstrom** [IonicaBizau/node.cobol#2]
After running _cobc -x example/main.cbl lib/node-exec-*.cbl_ and _./Main_ I get the error libcob: Cannot find module 'EXEC_NODEJS'.

When instead running _cobc -x example/main.cbl lib/*.cbl_ I get the expected behaviour.

**Comment by IonicaBizau** [comment]
@MartinSandstrom Thanks for the heads-up!

It's just that little `-` which should be removed. I guess I manually wrote the command int he example. Fixing now. :memo:

**Comment by MartinSandstrom** [comment]
Perfect :)

**Comment by IonicaBizau** [comment]
I fixed it in #3 and #4. :grin: 

:ship: **`1.0.3`** :tada:
